{:user {:plugins [[cider/cider-nrepl "0.13.0"]
                  [lein-try "0.4.3"]
                  [lein-midje "3.2.1"]
                  [lein-ancient "0.6.10"]
                  [lein-kibit "0.1.5"]
                  [lein-bikeshed "0.4.1"]
                  [lein-cloverage "1.0.9"]
                  [lein-datomic "0.2.0"]
                  [lein-plz "0.4.0-SNAPSHOT"]
                  [refactor-nrepl "2.3.0-SNAPSHOT"]
                  [jonase/eastwood "0.2.3"]]
        :dependencies [[org.clojure/tools.namespace "0.2.11"]
                       [org.clojure/tools.trace "0.7.9"]
                       [acyclic/squiggly-clojure "0.1.8"]
                       [slamhound "1.5.5"]]
        :aliases {"slamhound" ["run" "-m" "slam.hound"]}}}
