{:user {:plugins [[cider/cider-nrepl "0.8.2"]
                  [lein-try "0.4.3"]
                  [lein-midje "3.1.3"]
                  [lein-ancient "0.5.5"]
                  [lein-kibit "0.0.8"]
                  [lein-bikeshed "0.1.8"]
                  [lein-cloverage "1.0.2"]
                  [lein-datomic "0.2.0"]
                  [lein-plz "0.3.0"]
                  [refactor-nrepl "0.3.0-SNAPSHOT"]
                  [jonase/eastwood "0.2.0"]]
        :dependencies [[org.clojure/tools.namespace "0.2.7"]
                       [org.clojure/tools.trace "0.7.8"]
                       [acyclic/squiggly-clojure "0.1.2-SNAPSHOT"]
                       [slamhound "1.5.5"]]
        :aliases {"slamhound" ["run" "-m" "slam.hound"]}}}
